services:
  postgres:
    image: postgres:16
    container_name: homelab-postgres
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: homelab-minio
    restart: unless-stopped

    env_file:
      - .env

    command: server /data --console-address ":9001"

    volumes:
      - minio_data:/data

  auth-service:
    build: ../auth-service
    container_name: homelab-auth
    restart: unless-stopped

    env_file:
      - ../auth-service/.env

    depends_on:
      - postgres

  caddy:
    image: caddy:2
    container_name: homelab-caddy
    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ../auth-service/dashboard/dist:/var/www/frontend:ro

    depends_on:
      - auth-service

  cloudflared:
    image: cloudflare/cloudflared:2024.1.5
    container_name: homelab-tunnel
    restart: unless-stopped
    command: tunnel run
    env_file:
      - .env
    depends_on:
      - caddy

volumes:
  postgres_data:
  minio_data: